# -*- coding: utf-8 -*-
"""Unit2_List_Assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DD00lydX8nsd6_iZWMH00t_iV8c4YufR

# Intrdouction to Python - List - Assingment #2

## 1.Create a list of 5 of your favorite tv shows.  ?
"""

list = ['Enterprise', 'TNG', 'Deep Space Nine', 'Voyager', 'Discovery']

"""## 2.	Print the list in its original order"""

print(list)

"""## 3.	Use the sorted() function to print the list in alphabetical order.  How is sorted() different from sort()?"""

print(sorted(list))

"""## 4.	Print out your original list."""

print(list)

"""## 5.	Used sorted() to print your list in reverse alphabetical order."""

print(sorted(list, reverse = True))

"""## 6.	Create a message indicating how many favorite TV shows you have – use the len() function."""

print("I have", len(list), "favorite shows!")